version: '3'

services:

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - sharedLine

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8080:8080"
    networks:
      - sharedLine

networks:
  sharedLine:
