version: '3.9'

services:

    frontend:
        build:
            context: ./services/feedbacker-app
        command: npm run dev
        ports:
            - 8080:8080
            - 24678:24678
        environment:
            - PORT=8080
        volumes:
            - ./services/feedbacker-app:/app
            - nodemodules:/app/node_modules
        networks:
            - exposed-net

    backend:
        build:
            context: ./services/feedbacker-api
        env_file:
            - ./services/feedbacker-api/.env
        ports:
            - '3000:3000'
        networks:
            - exposed-net
        depends_on:
            - database

    # TODO implement mongo connection
    # database:
    #     image: mongo
    #     ports:
    #         - 27017:27017
    #     networks:
    #         - exposed-net
    #     # restart: always

volumes:
    nodemodules: {}

networks:
    privated-net:
        driver: bridge
    exposed-net:
        external: true
