version: '3'

services:

  frontend:
    build:
      context: ./services/feedbacker-app
    env_file:
      - ./services/feedbacker-app/.env
    ports:
      - "8080:8080"
    networks:
      - exposed-net

  backend:
    build:
      context: ./services/feedbacker-api
    ports:
      - "3001:3001"
    env_file:
      - ./services/feedbacker-api/.env
    networks:
      - exposed-net
  # database:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - exposed-net

networks:
  privated-net:
    driver: bridge
  exposed-net:
    external: true
