name: Widget e2e testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  cypress:
    defaults:
      run:
        working-directory: widget

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - run: yarn run build
        env:
          NODE_ENV: production

      - name: Run project locally
        run: |
          yarn serve
          $(yarn bin)/serve dist -s -p 8080 &

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:	
          working-directory: widget
          browser: chrome
          headless: true
